# Generated by Django 2.2.16 on 2020-10-10 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='first_name',
            new_name='employee_name',
        ),
    ]
